services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KLYP_DB_HOST: ${KLYP_DB_HOST}
      KLYP_DB_NAME: ${KLYP_DB_NAME}
      KLYP_DB_USER: ${KLYP_DB_USER}
      KLYP_DB_PASS: ${KLYP_DB_PASS}
    expose:
      - "80"
    networks:
      - coolify
    restart: unless-stopped

networks:
  coolify:
    external: true
    name: coolify
