services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    expose:
      - "80"
    networks:
      - coolify
    restart: unless-stopped

networks:
  coolify:
    external: true
    name: coolify
